name: Generate TLD list

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  generate:
    name: Update and release
    runs-on: ubuntu-latest

    env:
      CGO_ENABLED: 0

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Run go generate ./...
        run: go generate ./...

      - name: Check if we have a diff to commit
        id: diff
        run: |
          {
            echo "release_notes<<EOF"
            .github/update-list.sh
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Determine next version
        if: ${{steps.diff.outputs.release_notes}}
        id: next_version
        run: |
          next_version="$(git describe --tags --abbrev=0 | awk -F'.' '{printf "%s.%d.%d", $1, $2, $3 + 1}')"
          echo next_version="$next_version" >> "$GITHUB_OUTPUT"
          git tag "$next_version"
          git push origin $next_version

      - name: Commit changes
        if: ${{steps.diff.outputs.release_notes}}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: (auto) Update TLD list
          commit_user_name: Simon Sawert
          commit_user_email: simon@sawert.se
          file_pattern: tld.gen.go
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish release
        if: ${{steps.diff.outputs.release_notes}}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{steps.next_version.outputs.next_version}}
          body: ${{steps.diff.outputs.release_notes}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
